### PR TITLE
Rollup plugin for route templates

### PR DESCRIPTION
**Pull request by balinterdi**
Here is my write-up about the problem:

## rollup-hbs-plugin

The problem is that `rollup-hbs-plugin.ts` in @embroider/addon-dev creates a template-only module definition (it “synthesises a module”) when a JS module is attempted to be resolved and no module exists yet

For example, the `desktop/templates/caro-kann.js` is attempted to be resolved (see next section) and since that module doesn’t exist yet, it looks up the corresponding template, `desktop/templates/caro-kann.hbs`. This one exists so embroider assumes that it’s a template only component and it emits output 
corresponding to a template-only component.

## rollup-public-entrypoints

rollup-public-entrypoints matches *all hbs, ts, its, and gjs* files in the srcDir irrespective of what patterns the user passed in `addon.publicEntrypoints`.  That file will also detect template-only components and emit a chunk for them. I think that’s why `resolveId` is then called with the corresponding `.js` (so `desktop/templates/caro-kann.js` for `desktop/templates/caro-kann.hbs`) which triggers the `resolveId` hook in rollup-hbs-plugin (see above).

Here is [the Rollup docs say about `emitFile`](https://rollupjs.org/plugin-development/#this-emitfile):

> If the type is chunk, then this emits a new chunk with the given module id as entry point. To resolve it, the id will be passed through build hooks just like regular entry points, starting with [resolveId](https://rollupjs.org/plugin-development/#resolveid).

So instead of creating a template-only component for such a template, I’d have to modify the `rollup-hbs-plugin` to do the precompileTemplate on the hbs content and not set the component manager

-----

To make this (almost) work, I modified the `rollup-hbs-plugin` in `@embroider/addon-dev` so that it outputs (synthesizes) a different module when it comes across a route template (which it'd normally consider a template-only component).

I just needed to insert the condition that looks for a file in `templates` which I -for now- consider a route template:

```js
async function maybeSynthesizeComponentJS(context, source, importer, options) {
    let templateResolution = await context.resolve(correspondingTemplate(source), importer, {
        skipSelf: true,
        ...options,
    });
    if (!templateResolution) {
        return null;
    }
    // we're trying to resolve a JS module but only the corresponding HBS
    // file exists. Synthesize the template-only component JS.
    if (source.includes('templates')) {
        return {
            id: templateResolution.id.replace(/\.hbs$/, '.js'),
            meta: {
                "rollup-ember-route-templates-plugin": {
                    type: 'route-template'
                }
            }
        }
    }
    return {
        id: templateResolution.id.replace(/\.hbs$/, '.js'),
        meta: {
            'rollup-hbs-plugin': {
                type: 'template-only-component-js',
            },
        },
    };
}
```

Unfortunately, something still compiles that route template as if it was a component template (notice it calls `setComponentTemplate`) as the output in dist is the following:

```js
import { precompileTemplate } from '@ember/template-compilation';
import { setComponentTemplate } from '@ember/component';

var TEMPLATE = precompileTemplate("The Caro-Kann Opening\n\n<div class=\"image-container\">\n  <img src=\"/grand-prix/assets/images/caro-kann.webp\" alt=\"Caro Kann Opening\" />\n</div>");

var caroKann = setComponentTemplate(TEMPLATE, precompileTemplate("The Caro-Kann Opening\n\n<div class=\"image-container\">\n  <img src=\"/grand-prix/assets/images/caro-kann.webp\" alt=\"Caro Kann Opening\" />\n</div>"));

export { caroKann as default };
//# sourceMappingURL=caro-kann.js.map
```

----

Turns out it's [the `template-colocation-plugin`](https://github.com/embroider-build/embroider/blob/main/packages/shared-internals/src/template-colocation-plugin.ts) which is a Babel plugin which turns the simple `precompileTemplate` into the above code, which calls `setComponentTemplate`.

If remove that babel plugin from `babel.config.json` in the add-on, it's going to work – but we won't be able to use colocated components.

Strangely enough, the above code still works fine for a route template! I assume that the `setComponentTemplate` is flexible enough to just return the precompiled template (stored in `TEMPLATE`), if the 2nd argument is non-sensical?

So we can either just leave it as it is (with the non-sensical `setComponentTemplate` call in route template outputs) or make the Babel plugin not transform route templates.

### CODE REVIEW

**Comment by sandstrom** [comment]
## Collision

> Strangely enough, the above code still works fine for a route template!

I agree, it's totally fine. What will be the key/namespace that these components will live under?

We have e.g. both a route and a component named 'feedback'. Would those two collide? 

Or would it still be something like `routes/feedback`?

### Avoid collision manually

We could potentially avoid collisions manually too (by never naming a route and component the same thing), but that's some extra work, which we'd ideally like to avoid.

## V1

It seems like `template-colocation-plugin.ts` is only used/needed for v1 addons? Or at least the source code mentions something about that?

If so, do we have any v1 addons we need to support? If not, maybe we can just drop/disable that logic?

**Comment by balinterdi** [comment]
> It seems like template-colocation-plugin.ts is only used/needed for v1 addons? Or at least the source code mentions something about that?

We have to support colocated components (when the `.js` and `.hbs` files are next to each other) because that's what we use in the guest-client app. If I remove that babel plugin here's the output of the build process:

```js
import Component from '@glimmer/component';
import { getOwnConfig } from '@embroider/macros';

class GrandPrixComponent extends Component {
  get device() {
    return getOwnConfig().device;
  }
}

export { GrandPrixComponent as default };
//# sourceMappingURL=grand-prix.js.map
```

So the template part is completely missing.

Restoring the "@embroider/addon-dev/template-colocation-plugin" plugin also restores the correct build output:

```js
import Component from '@glimmer/component';
import { getOwnConfig } from '@embroider/macros';
import { precompileTemplate } from '@ember/template-compilation';
import { setComponentTemplate } from '@ember/component';

var TEMPLATE = precompileTemplate("<p class=\"main-message\">Hello from inside the ({{this.device}}) GrandPrix component!</p>\n\n<div class=\"image-container\">\n  <img src=\"/grand-prix/assets/images/grand-prix-attack.webp\" alt=\"Grand Prix\" />\n</div>");

class GrandPrixComponent extends Component {
  get device() {
    return getOwnConfig().device;
  }
}
setComponentTemplate(TEMPLATE, GrandPrixComponent);

export { GrandPrixComponent as default };
//# sourceMappingURL=grand-prix.js.map
```

**Comment by balinterdi** [comment]
> I agree, it's totally fine. What will be the key/namespace that these components will live under?

> We have e.g. both a route and a component named 'feedback'. Would those two collide?

There's no collision as Ember's resolver looks for templates and components in different places. I verified that in 87e3c80c80ea8424bf82bcd5bc0cea48c039e762 where I added a `caro-kann` component rendered from the `caro-kann` route (template).

**Comment by balinterdi** [comment]
I've also verified that a route, controller and route template work well together (when hoisted from a v2 addon) in [this commit](c6e52d85f4d0455af4780f62bd6d07edcbc6390a).

I'd merge this PR (just to "enrich" our prototype) and now move back to `guest-client` to apply what we learned here, and continue making the "home" page work there.

**Pull request merged**
